### PR TITLE
Fail upload if it uses more then available space

### LINKED ISSUE #179: Fail fast upload request if running out of disk space
Motion should return error to upload request if it is running out of disk space.
- Remaining disk space can be checked using cross platform pkg. https://github.com/shirou/gopsutil/
- Blob length can be checked using content-length request header. Explore below edge cases
  - How does this work with multi-part upload
  - How does transport compression impact this value
  - What if this header is missing

### PR DESCRIPTION
**Pull request by gammazero**
Before upload, check that more then the disk has more than the minimum free space. Upload up to the size limit that would exceed the available space.

Fixes #179

### CODE REVIEW

File: blob/local_store.go [hunk 1]
```diff
@@ -3,26 +3,42 @@ package blob
...
 type LocalStore struct {
-	dir string
+	dir          string
+	minFreeSpace uint64
 }
 
 // NewLocalStore instantiates a new LocalStore and uses the given dir as the place to store blobs.
 // Blobs are stored as flat files, named by their ID with .bin extension.
-func NewLocalStore(dir string) *LocalStore {
+func NewLocalStore(dir string, minFreeSpace uint64) *LocalStore {
```
Comment (elijaharita) [inline blob/local_store.go:34]: This new parameter might go better in a new config struct, since it's optional and what it represents is not obvious when reading a function call. Will also set up a better pattern for adding new options if ever needed in the future.

`myStore := NewLocalStore("/a/dir", 1024) // what is 1024?`

`myStore := NewLocalStore("/a/dir", LocalStoreConfig { MinFreeSpace: 1024 }) // better in my opinion`

**Review by elijaharita — APPROVED** [review]
Aside from one non-critical recommendation, looks good to me

File: blob/local_store.go (hunk 1 above)
Comment (gammazero) [reply blob/local_store.go]: I would prefer to pass Option parameters instead of a config. If passing a config, we would still want a source of default values, which the option provides.  I am implemented the optional parameter in the PR update.

As far as this: `myStore := NewLocalStore("/a/dir", 1024)`
... no one should ever do that anyway.  Code like that should always use a `const`, never a raw number. For example:
```go
const minFreeSpace = 2 * Gib // 2 Gib must remain free on disk
...
myStore := NewLocalStore("/a/dir", minFreeSpace)
```

Comment (elijaharita) [reply blob/local_store.go]: nice, option pattern is even better

fair point about minFreeSpace as a param. i guess i can't back it up more than that it feels weird - i like to see fundamental, required fields as direct constructor params and optional peripheral fields to go in a config struct or option pattern. 

definitely more philosophical than practical, would never deny a PR on these grounds, i just like discussing style : )

**Review by elijaharita — APPROVED** [review]
nice
